version: "3.8"

services: 
    db:
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: 63eaQB9wtLqmNBpg
            POSTGRES_DB: express
    api:
        build:
            context: .
            dockerfile: dev-Dockerfile
        command: npm run dev
        volumes: 
            - /usr/app/node_modules
            - ./:/usr/app
        ports: 
            - 3000:3000
        environment: 
            env_file: .env